---
- name: Update repo cache and install a few prerequisite packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - apt-transport-https
    - gnupg2

- name: Add the GPG key for the official Docker repo
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add the Docker repository to APT sources
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
    filename: docker
    mode: '0644'
  with_items:
    - "deb https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"

- name: Install Docker
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - docker-ce
  notify:
    - enable docker service
    - restart docker service
